import {ref} from "vue";

const userInfo = ref({
  userName: '张小三',
  role: '高级设计师',
  verified: true,
  userAvatar: 'https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png',
  coverImage: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
  userProfile: '创意设计师，专注于UI设计、插画和3D模型创作。热爱分享创意素材，致力于提升设计生态。',
  email: 'design@example.com',
  phone: '138****1234',
  field: 'UI设计 / 插画 / 3D模型',
  createTime: '2020年01月01日',
  website: 'https://design.example.com',
  stats: {
    uploads: 286,
    views: '25.8万',
    downloads: '3.2万',
    likes: '1.5万',
  },
  skills: [
    { name: 'Photoshop', level: 95, color: '#1890ff' },
    { name: 'Illustrator', level: 90, color: '#ff7a45' },
    { name: 'Figma', level: 85, color: '#52c41a' },
    { name: 'Blender', level: 75, color: '#722ed1' },
    { name: 'After Effects', level: 70, color: '#faad14' },
  ],
  categories: [
    { name: 'UI套件', color: '#108ee9' },
    { name: '图标', color: '#87d068' },
    { name: '插画', color: '#f50' },
    { name: '3D模型', color: '#722ed1' },
    { name: '动效', color: '#faad14' },
    { name: '字体', color: '#2db7f5' },
    { name: '样机', color: '#eb2f96' },
  ],
  popularMaterials: [
    {
      title: '现代科技UI组件库',
      thumbnail: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
      type: 'UI套件',
      date: '2023-05-16',
      views: 12563,
      downloads: 3452,
    },
    {
      title: '创意3D图标合集',
      thumbnail: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
      type: '图标',
      date: '2023-04-22',
      views: 9872,
      downloads: 2341,
    },
    {
      title: '手绘风格插画集',
      thumbnail: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
      type: '插画',
      date: '2023-03-10',
      views: 8765,
      downloads: 1987,
    },
    {
      title: '科技产品样机合集',
      thumbnail: 'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png',
      type: '样机',
      date: '2023-02-28',
      views: 7632,
      downloads: 1453,
    },
  ],
})
